---
# tasks file for roletest2
- name: hello
  debug:
    msg: "Hello from role in {{ role_path }}, whose name is {{ role_name }}"
- name: role names
  debug:
    var: role_names
- name: roles list
  debug:
    var: roles
- name: set my role_path
  set_fact:
    rp: "{{ role_path }}"
